version: '3.8'

services:
  books:
    build:
      context: ./books_service
      dockerfile: Dockerfile
    container_name: books
    ports:
      - "5001:8000"
    restart: always
    environment:
      - MONGO_URI=mongodb://mongodb:27017/BooksDB
    depends_on:
      - mongo

  loans:
    build:
      context: ./loans_service
      dockerfile: Dockerfile
    container_name: loans1
    ports:
      - "5002:8000"
    restart: always
    environment:
      - MONGO_URI=mongodb://mongodb:27017/LoansDB
    depends_on:
      - books
      - mongo

  loans2:
    build:
      context: ./loans_service
      dockerfile: Dockerfile
    container_name: loans2
    ports:
      - "5003:8000"
    restart: always
    environment:
      - MONGO_URI=mongodb://mongodb:27017/LoansDB
    depends_on:
      - books
      - mongo

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - books
      - loans
      - loans2
