version: '3.8'

services:
  books:
    build: .
    container_name: books
    ports:
      - "5001:8000"
    restart: always
    environment:
      - MONGO_URI=mongodb://mongodb:27017/BooksDB
    depends_on:
      - mongo
    command: [ "flask", "run", "--host=0.0.0.0", "--port=8000" ]

  loans:
    build: .
    container_name: loans1
    ports:
      - "5002:8000"
    restart: always
    environment:
      - MONGO_URI=mongodb://mongodb:27017/BooksDB
    depends_on:
      - mongo
    command: [ "flask", "run", "--host=0.0.0.0", "--port=8000" ]

  loans2:
    build: .
    container_name: loans2
    ports:
      - "5003:8000"
    restart: always
    environment:
      - MONGO_URI=mongodb://mongodb:27017/BooksDB
    depends_on:
      - mongo
    command: [ "flask", "run", "--host=0.0.0.0", "--port=8000" ]

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - books
      - loans
      - loans2

volumes:
  mongo-data:
