version: '3.8'

services:
  books:
    build: ./books_service
    container_name: books
    ports:
      - "5001:80"
    expose:
      - 80
    restart: always
    environment:
      - MONGO_URI=mongodb://mongo:27017/BooksDB
    depends_on:
      - mongo

  loans:
    build: ./loans_service
    container_name: loans1
    ports:
      - "5002:80"
    expose:
      - 80
    restart: always
    environment:
      - MONGO_URI=mongodb://mongo:27017/LoansDB
    depends_on:
      - books
      - mongo

  loans2:
    build: ./loans_service
    container_name: loans2
    ports:
      - "5003:80"
    expose:
      - 80
    restart: always
    environment:
      - MONGO_URI=mongodb://mongo:27017/BooksDB
    depends_on:
      - books
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    restart: always
    
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    expose:
      - 80
    restart: always
    depends_on:
      - books
      - loans
      - loans2
